### ISSUE TITLE
.Net Core release?

### ISSUE THREAD

**Issue by Ponant** [lemonwaysas/c-sharp-client-directkit-xml#1]
Hi,
Is it possible to make this compatible with .Net Core?
Thanks!

**Comment by duongphuhiep** [comment]
Hi,

We've never try this option, but it should be possible.. 

Option 1) use [HttpClient](https://docs.microsoft.com/en-us/dotnet/core/api/system.net.http.httpclient) to communicate with the **directkitjson2**: it is only the mater of sending and receiving Json messages via HTTP POST.
* http://documentation.lemonway.fr/api-en/directkit/overview/requests-and-responses

Option 2) You can also use the **directkitxml**. If there is no SoapClient library for .NET core, we can always use HttpClient to communicate with the directkitxml via SOAP protocol
* https://long2know.com/2016/07/consuming-a-soap-service-using-httpclient/

**Comment by Ponant** [comment]
Thank you very much for your feedback. Is SoapClient more secure? Anyhow, it does not seem that SOAP is supported.

**Comment by duongphuhiep** [comment]
no, they are basically all HTTP protocol, the only different between SOAP and JSON is the request reponse format

**Comment by Ponant** [comment]
Hi,
I thought about your responses and went through the documentation. Although an implementation should be manageable, I would strongly recommend (and would appreciate, too) that you provide a sample for ASP.NET Core (1.1 and later 1.2 in mid 2017) with one View and configuring the Startup.cs correctly to inject the service(s). The issue of payments is just too critical to be left for anyone to configure it. It is wise to say that .Net Core will be the prime choice for many devs using MS technologies, especially among startups, so I am confident that Lemonway would benefit from it.
Greetings,

**Comment by duongphuhiep** [comment]
Hi,

You don't need any fancy library or injecting anything. 

I developed an example to show you how to call our service with .NET core
https://github.com/lemonwaysas/csharp-client-directkit-json2

You can use the same code in any of your application (ASP.Net core, Winform, Silverlight, WCF, Windows Service application..)

You often don't need to use all the functions of our API, but only some of them.
It is up to you to decide when / what / how you will use our service in your application. For example
When user click a button on your application, you will create a wallet / transfer money from some wallet to other... or redirect user to a payment page...

cheers

**Comment by Ponant** [comment]
That is great, thanks a lot and again I think that effort will be good for lemonway.

**Comment by duongphuhiep** [comment]
there is other customer who ask the same question as you, so, I did a more complet solution for ASP.NET core

https://github.com/lemonwaysas/aspdotnet-client-directkit-json2

if you have other implementation that you can share, I'll be interested..

Thank you

**Comment by Ponant** [comment]
OK great, I will do it if I have another implementation. BTW, your first implementation did not require the user to have an account, which I think would have been handy too in the new implementation (perhaps as commented code). Cheers
